export const kabir_neutral = [
  '................',
  '.....EEEEEE.....',
  '....EEEEEEEE....',
  '....E8C8C8CE....',
  '....CCCCCCCC....',
  '....CCECCECC....',
  '....CCCCCCCC....',
  '....CC5CC5CC....',
  '....CCCCCCCC....',
  '.....CCCCCC.....',
  '....6CCCCCC6....',
  '...66CCCCCC66...',
  '..666666666666..',
  '..66.666666.66..',
  '..66.666666.66..',
  '................',
];

export const kabir_happy = [
  '................',
  '.....EEEEEE.....',
  '....EEEEEEEE....',
  '....E8C8C8CE....',
  '....CCCCCCCC....',
  '....CCECCECC....',
  '....CCCCCCCC....',
  '....CC.CC.CC....',
  '....CCCCCCCC....',
  '.....CC55CC.....',
  '....6CCCCCC6....',
  '...66CCCCCC66...',
  '..666666666666..',
  '..66.666666.66..',
  '..66.666666.66..',
  '................',
];

export const kabir_worried = [
  '................',
  '.....EEEEEE.....',
  '....EEEEEEEE....',
  '....E8C8C8CE....',
  '....CCCCCCCC....',
  '...ECCECCECCE...',
  '....CCCCCCCC....',
  '....CC5CC5CC....',
  '....C5CCCC5C....',
  '.....C5555C.....',
  '....6CCCCCC6....',
  '...66CCCCCC66...',
  '..666666666666..',
  '..66.666666.66..',
  '..66.666666.66..',
  '................',
];

export const nila_neutral = [
  '................',
  '.....EEEEEE.....',
  '....EEEEEEEE....',
  '....ECCCCCCE....',
  '....CCCCCCCC....',
  '....CCECCECC....',
  '....CCCCCCCC....',
  '....CC5CC5CC....',
  '....CCCCCCCC....',
  '.....CCCCCC.....',
  '...11CCCCCC11...',
  '..1111CCCC1111..',
  '..111111111111..',
  '..11.111111.11..',
  '..11.111111.11..',
  '................',
];

export const nila_happy = [
  '................',
  '.....EEEEEE.....',
  '....EEEEEEEE....',
  '....ECCCCCCE....',
  '....CCCCCCCC....',
  '....CCECCECC....',
  '....CCCCCCCC....',
  '....CC.CC.CC....',
  '....CCCCCCCC....',
  '.....CC55CC.....',
  '...11CCCCCC11...',
  '..1111CCCC1111..',
  '..111111111111..',
  '..11.111111.11..',
  '..11.111111.11..',
  '................',
];

export const nila_worried = [
  '................',
  '.....EEEEEE.....',
  '....EEEEEEEE....',
  '....ECCCCCCE....',
  '....CCCCCCCC....',
  '...ECCECCECCE...',
  '....CCCCCCCC....',
  '....CC5CC5CC....',
  '....C5CCCC5C....',
  '.....C5555C.....',
  '...11CCCCCC11...',
  '..1111CCCC1111..',
  '..111111111111..',
  '..11.111111.11..',
  '..11.111111.11..',
  '................',
];

export const sharmin_neutral = [
  '................',
  '.....EFFFFE.....',
  '....EFFFFFFE....',
  '....EDCDCDCDE...',
  '....DDDDDDDD....',
  '....DDECDDECD...',
  '....DDDDDDDD....',
  '....DD5DD5DD....',
  '....DDDDDDDD....',
  '.....DDDDDD.....',
  '....ADDDDDDA....',
  '...AAADDDDDAAA..',
  '..AAAAAAAAAAAA..',
  '..AA.AAAAAA.AA..',
  '..AA.AAAAAA.AA..',
  '................',
];

export const tanvir_neutral = [
  '................',
  '....E.EEEEEE....',
  '...EEEEEEEEEE...',
  '...ECDCCDCDCE...',
  '...CCCCCCCCCC...',
  '...CCCECCCECC...',
  '...CCCCCCCCCC...',
  '...CC5CCCC5CC...',
  '...CCCCCCCCCC...',
  '....CCCCCCCC....',
  '...7CCCCCCCC7...',
  '..777CCCCCC777..',
  '..777777777777..',
  '..77.777777.77..',
  '..77.777777.77..',
  '................',
];

export const alam_neutral = [
  '................',
  '.....EEEEEE.....',
  '....EEFFFFEE....',
  '....ECDCDCDE....',
  '....DDDDDDDD....',
  '....DDECDDECD...',
  '....DDDDDDDD....',
  '....DDEDDEDD....',
  '....DDDDDDDD....',
  '.....DDDDDD.....',
  '....FDDDDDDF....',
  '...FFFDDDDFFFF..',
  '..FFFFFFFFFFFF..',
  '..FF.FFFFFF.FF..',
  '..FF.FFFFFF.FF..',
  '................',
];

export const rafiq_neutral = [
  '................',
  '....BBBBBBBB....',
  '...BBBBBBBBBB...',
  '...BDDCCDCDDB...',
  '...DDDDDDDDDD...',
  '...DDDDDDDDDD...',
  '...DDDDDDDDDD...',
  '...DD5DDDD5DD...',
  '...DDDDDDDDDD...',
  '....DD8888DD....',
  '....BDDDDDDDB...',
  '...BBBDDDDDBBB..',
  '..BBBBBBBBBBBB..',
  '..BB.BBBBBB.BB..',
  '..BB.BBBBBB.BB..',
  '................',
];

export const avatar_boy = [
  '................',
  '.....EEEEEE.....',
  '....EEEEEEEE....',
  '....ECCCCCCE....',
  '....CCCCCCCC....',
  '....CCECCECC....',
  '....CCCCCCCC....',
  '....CC5CC5CC....',
  '....CCCCCCCC....',
  '.....CCCCCC.....',
  '....9CCCCCC9....',
  '...99CCCCCC99...',
  '..999999999999..',
  '..99.999999.99..',
  '..99.999999.99..',
  '................',
];

export const avatar_girl = [
  '................',
  '....EEEEEEEE....',
  '...EEEEEEEEEE...',
  '...EECCCCCCEE...',
  '...ECCCCCCCCE...',
  '...ECEECCEECE...',
  '...ECCCCCCCCE...',
  '...ECCCCCCCCE...',
  '...ECCCCCCCCE...',
  '...EEECCCCEEE...',
  '..EEEECCCCEEEE..',
  '..AAEEEEEEEEAA..',
  '..AAAAAAAAAAAA..',
  '..AA.AAAAAA.AA..',
  '..AA.AAAAAA.AA..',
  '................',
];

export const portraits = {
  avatar_boy,
  avatar_girl,
  kabir_neutral,
  kabir_happy,
  kabir_worried,
  nila_neutral,
  nila_happy,
  nila_worried,
  sharmin_neutral,
  tanvir_neutral,
  alam_neutral,
  rafiq_neutral,
};
